services:
  - type: web
    name: erp-production-dg
    runtime: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python render_setup.py
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: false
      - key: STREAMLIT_SERVER_FILE_WATCHER_TYPE
        value: none
    disk:
      name: erp-data
      mountPath: /home/render/project/data
      sizeGB: 1