# .streamlit/config.toml

# Documentation du Thème: https://docs.streamlit.io/library/advanced-features/theming

[theme]
# Couleur primaire utilisée pour les éléments interactifs
# Exemple: Tailwind Blue 500
primaryColor="#3B82F6"

# Couleur de fond principale de l'application
# Exemple: Tailwind Gray 50
backgroundColor="#F9FAFB"

# Couleur de fond pour les éléments comme la sidebar, les cartes, les expanders, etc.
# Blanc pur pour un bon contraste
secondaryBackgroundColor="#FFFFFF"

# Couleur de base du texte
# Exemple: Tailwind Gray 700
textColor="#374151"

# # Police de caractères. Déclarée ici pour la configuration Streamlit,
# # mais l'application via CSS dans 'app.py' ou 'style.css' est souvent plus robuste.
# # Assurez-vous que la police 'Inter' est chargée via Google Fonts dans app.py.
# font="Inter" # <-- LIGNE COMMENTÉE: Cause l'avertissement "Inter is an invalid value".
                # La police est déjà chargée et appliquée via CSS (app.py/style.css),
                # cette ligne n'est donc pas nécessaire ici et peut être supprimée ou commentée.

# --- Autres options de configuration utiles ---

[server]
# Option importante pour le déploiement (évite d'ouvrir un navigateur sur le serveur)
headless = true

# Optionnel: Port si vous lancez localement avec un port spécifique (défaut 8501)
# port = 8501

[client]
# Masque une partie du menu hamburger Streamlit pour une interface plus propre
# Options: "developer", "viewer", "minimal"
toolbarMode = "minimal"

[browser]
# Désactive la collecte de statistiques d'utilisation par Streamlit (bonne pratique pour la confidentialité)
gatherUsageStats = false

# Optionnel: Si vous voulez définir l'ordre des onglets dans le navigateur (peu utilisé)
# serverAddress = "votre_domaine_ou_ip"

# Optionnel: Limites de taille pour les uploads (Streamlit a ses propres limites aussi)
# La limite est généralement mieux gérée au niveau du serveur web (nginx, etc.) si applicable,
# ou par les limites de la plateforme (Hugging Face Spaces).
# maxUploadSize = 200 # En Megabytes. La valeur par défaut de Streamlit est 200Mo.
                      # Augmenter ici n'a d'effet que si le serveur le permet aussi.
                      # Pour Hugging Face, les limites de la plateforme prévalent souvent.